//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Admin_Rentals
    {
        public C_Admin_Rentals()
        {
            this.C_DudaCliente = new HashSet<C_DudaCliente>();
        }
    
        public int adr_id_admin { get; set; }
        public string adr_Cedula { get; set; }
        public string adr_Nombre { get; set; }
        public string adr_SegundoNombre { get; set; }
        public string adr_PrimerApellido { get; set; }
        public string adr_SegundoApellido { get; set; }
        public Nullable<System.DateTime> adr_FechaNacimiento { get; set; }
        public string adr_TelefonoCasa { get; set; }
        public string adr_TelefonoCelular { get; set; }
        public string adr_Email { get; set; }
    
        public virtual ICollection<C_DudaCliente> C_DudaCliente { get; set; }
    }
}
