//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Contratos
    {
        public int id_ctr_contrato { get; set; }
        public int fk_cli_cliente { get; set; }
        public string ctr_numeroContrato { get; set; }
        public System.DateTime ctr_fechainicio { get; set; }
        public Nullable<System.DateTime> ctr_fechafinalizacion { get; set; }
        public decimal ctr_monto { get; set; }
        public Nullable<bool> ctr_activo { get; set; }
        public string ctr_file { get; set; }
        public int fk_alq_id_propiedad { get; set; }
    
        public virtual C_Alquiler C_Alquiler { get; set; }
        public virtual C_Cliente C_Cliente { get; set; }
    }
}
