//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Contratos
    {
        public C_Contratos()
        {
            this.C_Tiquete = new HashSet<C_Tiquete>();
            this.C_ReportePago = new HashSet<C_ReportePago>();
        }
    
        public int id_ctr_contrato { get; set; }
        public int fk_cli_cliente { get; set; }
        public string ctr_numeroContrato { get; set; }
        public System.DateTime ctr_fechainicio { get; set; }
        public Nullable<System.DateTime> ctr_fechafinalizacion { get; set; }
        public decimal ctr_monto { get; set; }
        public Nullable<bool> ctr_activo { get; set; }
        public string ctr_file { get; set; }
        public int fk_alq_id_propiedad { get; set; }
        public Nullable<int> fk_adr_id_admin { get; set; }
        public Nullable<System.DateTime> ctr_fechaPago { get; set; }
    
        public virtual C_Admin_Rentals C_Admin_Rentals { get; set; }
        public virtual C_Alquiler C_Alquiler { get; set; }
        public virtual C_Cliente C_Cliente { get; set; }
        public virtual ICollection<C_Tiquete> C_Tiquete { get; set; }
        public virtual ICollection<C_ReportePago> C_ReportePago { get; set; }
    }
}
