//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Distrito
    {
        public C_Distrito()
        {
            this.C_Alquiler = new HashSet<C_Alquiler>();
        }
    
        public int Id_Distrito { get; set; }
        public string Nombre { get; set; }
        public int Id_Canton { get; set; }
    
        public virtual ICollection<C_Alquiler> C_Alquiler { get; set; }
        public virtual C_Canton C_Canton { get; set; }
    }
}
