//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DudaCliente
    {
        public int ddc_id_Duda { get; set; }
        public string ddc_Nombre { get; set; }
        public string ddc_PrimerApellido { get; set; }
        public string ddc_SegundoApellido { get; set; }
        public string ddc_Telefono { get; set; }
        public string ddc_Email { get; set; }
        public string ddc_Comentario { get; set; }
        public Nullable<System.DateTime> ddc_FechaHoraApertura { get; set; }
        public Nullable<int> cli_Cliente { get; set; }
        public Nullable<int> adr_id_admin { get; set; }
    
        public virtual C_Admin_Rentals C_Admin_Rentals { get; set; }
        public virtual C_Cliente C_Cliente { get; set; }
    }
}
