//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Provincia
    {
        public C_Provincia()
        {
            this.C_Alquiler = new HashSet<C_Alquiler>();
            this.C_Canton = new HashSet<C_Canton>();
            this.C_Proveedor = new HashSet<C_Proveedor>();
        }
    
        public int Id_Provincia { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<C_Alquiler> C_Alquiler { get; set; }
        public virtual ICollection<C_Canton> C_Canton { get; set; }
        public virtual ICollection<C_Proveedor> C_Proveedor { get; set; }
    }
}
