//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Proveedor
    {
        public C_Proveedor()
        {
            this.C_Tiquete = new HashSet<C_Tiquete>();
        }
    
        public int prv_IDProveedor { get; set; }
        public string prv_NombreVariable { get; set; }
        public string prv_NombreRepresentante { get; set; }
        public string prv_PrimerApellido { get; set; }
        public string prv_SegundoApellido { get; set; }
        public string prv_CedulaRepresentante { get; set; }
        public string prv_CedulaJuridica { get; set; }
        public string prv_Telefono { get; set; }
        public string prv_Email { get; set; }
        public string prv_TipoProveedor { get; set; }
        public int Id_Distrito { get; set; }
        public int Id_Canton { get; set; }
        public int Id_Provincia { get; set; }
        public string prv_OtrasSenas { get; set; }
        public Nullable<bool> alq_Activo { get; set; }
    
        public virtual C_Canton C_Canton { get; set; }
        public virtual C_Distrito C_Distrito { get; set; }
        public virtual C_Provincia C_Provincia { get; set; }
        public virtual ICollection<C_Tiquete> C_Tiquete { get; set; }
    }
}
