//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ReportePago
    {
        public int rpp_IDReportarPago { get; set; }
        public int fk_cli_cliente { get; set; }
        public int fk_ctr_IDContrato { get; set; }
        public Nullable<System.DateTime> rpp_FechaPagoRecibido { get; set; }
        public Nullable<bool> rpp_estadoDePago { get; set; }
        public string rpp_DetallesDePago { get; set; }
    
        public virtual C_Cliente C_Cliente { get; set; }
        public virtual C_Contratos C_Contratos { get; set; }
    }
}
