//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Tiquete
    {
        public int tqt_id { get; set; }
        public Nullable<int> fk_id_ctr_contrato { get; set; }
        public string tqt_tipo_problema { get; set; }
        public Nullable<bool> tqt_activo { get; set; }
        public string tqt_descripcion { get; set; }
        public string tqt_nota_reparacion { get; set; }
        public Nullable<System.DateTime> tqt_fecha_inicio { get; set; }
        public Nullable<System.DateTime> tqt_fecha_finalizacion { get; set; }
        public Nullable<int> fk_prv_idProveedor { get; set; }
        public string tqt_titulo { get; set; }
        public Nullable<decimal> tqt_precio_reparacion { get; set; }
        public string tqt_estado { get; set; }
    
        public virtual C_Contratos C_Contratos { get; set; }
        public virtual C_Proveedor C_Proveedor { get; set; }
    }
}
