//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Usuario
    {
        public string usuario { get; set; }
        public string enc_password { get; set; }
        public bool activo { get; set; }
        public int tipo { get; set; }
        public int id_usuario { get; set; }
    }
}
