//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSmartRentals.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SmartRentalsEntities1 : DbContext
    {
        public SmartRentalsEntities1()
            : base("name=SmartRentalsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_Admin_Rentals> C_Admin_Rentals { get; set; }
        public DbSet<C_Alquiler> C_Alquiler { get; set; }
        public DbSet<C_Canton> C_Canton { get; set; }
        public DbSet<C_Cliente> C_Cliente { get; set; }
        public DbSet<C_Contratos> C_Contratos { get; set; }
        public DbSet<C_Distrito> C_Distrito { get; set; }
        public DbSet<C_Proveedor> C_Proveedor { get; set; }
        public DbSet<C_Provincia> C_Provincia { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<C_Tiquete> C_Tiquete { get; set; }
        public DbSet<C_Usuario> C_Usuario { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_EliminarAdminRental(Nullable<int> v_id)
        {
            var v_idParameter = v_id.HasValue ?
                new ObjectParameter("v_id", v_id) :
                new ObjectParameter("v_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarAdminRental", v_idParameter);
        }
    
        public virtual int sp_EliminarCliente(Nullable<int> c_idCliente)
        {
            var c_idClienteParameter = c_idCliente.HasValue ?
                new ObjectParameter("c_idCliente", c_idCliente) :
                new ObjectParameter("c_idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarCliente", c_idClienteParameter);
        }
    
        public virtual int sp_EliminarProveedor(Nullable<int> v_id)
        {
            var v_idParameter = v_id.HasValue ?
                new ObjectParameter("v_id", v_id) :
                new ObjectParameter("v_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarProveedor", v_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_InsertarAdminRental(string v_Cedula, string v_Nombre, string v_SegundoNombre, string v_PrimerApellido, string v_SegundoApellido, Nullable<System.DateTime> v_FechaNacimiento, string v_TelefonoCasa, string v_TelefonoCelular, string v_Email)
        {
            var v_CedulaParameter = v_Cedula != null ?
                new ObjectParameter("v_Cedula", v_Cedula) :
                new ObjectParameter("v_Cedula", typeof(string));
    
            var v_NombreParameter = v_Nombre != null ?
                new ObjectParameter("v_Nombre", v_Nombre) :
                new ObjectParameter("v_Nombre", typeof(string));
    
            var v_SegundoNombreParameter = v_SegundoNombre != null ?
                new ObjectParameter("v_SegundoNombre", v_SegundoNombre) :
                new ObjectParameter("v_SegundoNombre", typeof(string));
    
            var v_PrimerApellidoParameter = v_PrimerApellido != null ?
                new ObjectParameter("v_PrimerApellido", v_PrimerApellido) :
                new ObjectParameter("v_PrimerApellido", typeof(string));
    
            var v_SegundoApellidoParameter = v_SegundoApellido != null ?
                new ObjectParameter("v_SegundoApellido", v_SegundoApellido) :
                new ObjectParameter("v_SegundoApellido", typeof(string));
    
            var v_FechaNacimientoParameter = v_FechaNacimiento.HasValue ?
                new ObjectParameter("v_FechaNacimiento", v_FechaNacimiento) :
                new ObjectParameter("v_FechaNacimiento", typeof(System.DateTime));
    
            var v_TelefonoCasaParameter = v_TelefonoCasa != null ?
                new ObjectParameter("v_TelefonoCasa", v_TelefonoCasa) :
                new ObjectParameter("v_TelefonoCasa", typeof(string));
    
            var v_TelefonoCelularParameter = v_TelefonoCelular != null ?
                new ObjectParameter("v_TelefonoCelular", v_TelefonoCelular) :
                new ObjectParameter("v_TelefonoCelular", typeof(string));
    
            var v_EmailParameter = v_Email != null ?
                new ObjectParameter("v_Email", v_Email) :
                new ObjectParameter("v_Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarAdminRental", v_CedulaParameter, v_NombreParameter, v_SegundoNombreParameter, v_PrimerApellidoParameter, v_SegundoApellidoParameter, v_FechaNacimientoParameter, v_TelefonoCasaParameter, v_TelefonoCelularParameter, v_EmailParameter);
        }
    
        public virtual int sp_InsertarAlquiler(string v_UbicacionExacta, string v_TipoPropiedad, string v_Detalles, Nullable<int> v_Distrito, Nullable<int> v_Canton, Nullable<int> v_Provincia, string v_ImagenURL, Nullable<bool> v_Activo)
        {
            var v_UbicacionExactaParameter = v_UbicacionExacta != null ?
                new ObjectParameter("v_UbicacionExacta", v_UbicacionExacta) :
                new ObjectParameter("v_UbicacionExacta", typeof(string));
    
            var v_TipoPropiedadParameter = v_TipoPropiedad != null ?
                new ObjectParameter("v_TipoPropiedad", v_TipoPropiedad) :
                new ObjectParameter("v_TipoPropiedad", typeof(string));
    
            var v_DetallesParameter = v_Detalles != null ?
                new ObjectParameter("v_Detalles", v_Detalles) :
                new ObjectParameter("v_Detalles", typeof(string));
    
            var v_DistritoParameter = v_Distrito.HasValue ?
                new ObjectParameter("v_Distrito", v_Distrito) :
                new ObjectParameter("v_Distrito", typeof(int));
    
            var v_CantonParameter = v_Canton.HasValue ?
                new ObjectParameter("v_Canton", v_Canton) :
                new ObjectParameter("v_Canton", typeof(int));
    
            var v_ProvinciaParameter = v_Provincia.HasValue ?
                new ObjectParameter("v_Provincia", v_Provincia) :
                new ObjectParameter("v_Provincia", typeof(int));
    
            var v_ImagenURLParameter = v_ImagenURL != null ?
                new ObjectParameter("v_ImagenURL", v_ImagenURL) :
                new ObjectParameter("v_ImagenURL", typeof(string));
    
            var v_ActivoParameter = v_Activo.HasValue ?
                new ObjectParameter("v_Activo", v_Activo) :
                new ObjectParameter("v_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarAlquiler", v_UbicacionExactaParameter, v_TipoPropiedadParameter, v_DetallesParameter, v_DistritoParameter, v_CantonParameter, v_ProvinciaParameter, v_ImagenURLParameter, v_ActivoParameter);
        }
    
        public virtual int sp_InsertarCliente(string cli_Cedula, string cli_Nombre, string cli_SegundoNombre, string cli_PrimerApellido, string cli_SegundoApellido, Nullable<System.DateTime> cli_FechaNacimiento, string cli_TelefonoCasa, string cli_TelefonoCelular, string cli_Email, Nullable<bool> v_Activo)
        {
            var cli_CedulaParameter = cli_Cedula != null ?
                new ObjectParameter("cli_Cedula", cli_Cedula) :
                new ObjectParameter("cli_Cedula", typeof(string));
    
            var cli_NombreParameter = cli_Nombre != null ?
                new ObjectParameter("cli_Nombre", cli_Nombre) :
                new ObjectParameter("cli_Nombre", typeof(string));
    
            var cli_SegundoNombreParameter = cli_SegundoNombre != null ?
                new ObjectParameter("cli_SegundoNombre", cli_SegundoNombre) :
                new ObjectParameter("cli_SegundoNombre", typeof(string));
    
            var cli_PrimerApellidoParameter = cli_PrimerApellido != null ?
                new ObjectParameter("cli_PrimerApellido", cli_PrimerApellido) :
                new ObjectParameter("cli_PrimerApellido", typeof(string));
    
            var cli_SegundoApellidoParameter = cli_SegundoApellido != null ?
                new ObjectParameter("cli_SegundoApellido", cli_SegundoApellido) :
                new ObjectParameter("cli_SegundoApellido", typeof(string));
    
            var cli_FechaNacimientoParameter = cli_FechaNacimiento.HasValue ?
                new ObjectParameter("cli_FechaNacimiento", cli_FechaNacimiento) :
                new ObjectParameter("cli_FechaNacimiento", typeof(System.DateTime));
    
            var cli_TelefonoCasaParameter = cli_TelefonoCasa != null ?
                new ObjectParameter("cli_TelefonoCasa", cli_TelefonoCasa) :
                new ObjectParameter("cli_TelefonoCasa", typeof(string));
    
            var cli_TelefonoCelularParameter = cli_TelefonoCelular != null ?
                new ObjectParameter("cli_TelefonoCelular", cli_TelefonoCelular) :
                new ObjectParameter("cli_TelefonoCelular", typeof(string));
    
            var cli_EmailParameter = cli_Email != null ?
                new ObjectParameter("cli_Email", cli_Email) :
                new ObjectParameter("cli_Email", typeof(string));
    
            var v_ActivoParameter = v_Activo.HasValue ?
                new ObjectParameter("v_Activo", v_Activo) :
                new ObjectParameter("v_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarCliente", cli_CedulaParameter, cli_NombreParameter, cli_SegundoNombreParameter, cli_PrimerApellidoParameter, cli_SegundoApellidoParameter, cli_FechaNacimientoParameter, cli_TelefonoCasaParameter, cli_TelefonoCelularParameter, cli_EmailParameter, v_ActivoParameter);
        }
    
        public virtual int sp_InsertarContrato(Nullable<int> v_fk_cli_cliente, string v_ctr_numero, Nullable<System.DateTime> v_ctr_fechainicio, Nullable<System.DateTime> v_ctr_fechafinalizacion, Nullable<decimal> v_ctr_monto, Nullable<bool> v_ctr_activo, string v_ctr_file, Nullable<int> v_fk_alq_id_propiedad, Nullable<int> v_fk_adr_id_admin, Nullable<System.DateTime> v_fechaPago)
        {
            var v_fk_cli_clienteParameter = v_fk_cli_cliente.HasValue ?
                new ObjectParameter("v_fk_cli_cliente", v_fk_cli_cliente) :
                new ObjectParameter("v_fk_cli_cliente", typeof(int));
    
            var v_ctr_numeroParameter = v_ctr_numero != null ?
                new ObjectParameter("v_ctr_numero", v_ctr_numero) :
                new ObjectParameter("v_ctr_numero", typeof(string));
    
            var v_ctr_fechainicioParameter = v_ctr_fechainicio.HasValue ?
                new ObjectParameter("v_ctr_fechainicio", v_ctr_fechainicio) :
                new ObjectParameter("v_ctr_fechainicio", typeof(System.DateTime));
    
            var v_ctr_fechafinalizacionParameter = v_ctr_fechafinalizacion.HasValue ?
                new ObjectParameter("v_ctr_fechafinalizacion", v_ctr_fechafinalizacion) :
                new ObjectParameter("v_ctr_fechafinalizacion", typeof(System.DateTime));
    
            var v_ctr_montoParameter = v_ctr_monto.HasValue ?
                new ObjectParameter("v_ctr_monto", v_ctr_monto) :
                new ObjectParameter("v_ctr_monto", typeof(decimal));
    
            var v_ctr_activoParameter = v_ctr_activo.HasValue ?
                new ObjectParameter("v_ctr_activo", v_ctr_activo) :
                new ObjectParameter("v_ctr_activo", typeof(bool));
    
            var v_ctr_fileParameter = v_ctr_file != null ?
                new ObjectParameter("v_ctr_file", v_ctr_file) :
                new ObjectParameter("v_ctr_file", typeof(string));
    
            var v_fk_alq_id_propiedadParameter = v_fk_alq_id_propiedad.HasValue ?
                new ObjectParameter("v_fk_alq_id_propiedad", v_fk_alq_id_propiedad) :
                new ObjectParameter("v_fk_alq_id_propiedad", typeof(int));
    
            var v_fk_adr_id_adminParameter = v_fk_adr_id_admin.HasValue ?
                new ObjectParameter("v_fk_adr_id_admin", v_fk_adr_id_admin) :
                new ObjectParameter("v_fk_adr_id_admin", typeof(int));
    
            var v_fechaPagoParameter = v_fechaPago.HasValue ?
                new ObjectParameter("v_fechaPago", v_fechaPago) :
                new ObjectParameter("v_fechaPago", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarContrato", v_fk_cli_clienteParameter, v_ctr_numeroParameter, v_ctr_fechainicioParameter, v_ctr_fechafinalizacionParameter, v_ctr_montoParameter, v_ctr_activoParameter, v_ctr_fileParameter, v_fk_alq_id_propiedadParameter, v_fk_adr_id_adminParameter, v_fechaPagoParameter);
        }
    
        public virtual int sp_InsertarProveedor(string prv_NombreVariable, string prv_NombreRepresentante, string prv_PrimerApellido, string prv_SegundoApellido, string prv_CedulaRepresentante, string prv_CedulaJuridica, string prv_Telefono, string prv_Email, string prv_TipoProveedor, Nullable<int> v_Distrito, Nullable<int> v_Canton, Nullable<int> v_Provincia, string prv_OtrasSenas, Nullable<bool> v_Activo)
        {
            var prv_NombreVariableParameter = prv_NombreVariable != null ?
                new ObjectParameter("prv_NombreVariable", prv_NombreVariable) :
                new ObjectParameter("prv_NombreVariable", typeof(string));
    
            var prv_NombreRepresentanteParameter = prv_NombreRepresentante != null ?
                new ObjectParameter("prv_NombreRepresentante", prv_NombreRepresentante) :
                new ObjectParameter("prv_NombreRepresentante", typeof(string));
    
            var prv_PrimerApellidoParameter = prv_PrimerApellido != null ?
                new ObjectParameter("prv_PrimerApellido", prv_PrimerApellido) :
                new ObjectParameter("prv_PrimerApellido", typeof(string));
    
            var prv_SegundoApellidoParameter = prv_SegundoApellido != null ?
                new ObjectParameter("prv_SegundoApellido", prv_SegundoApellido) :
                new ObjectParameter("prv_SegundoApellido", typeof(string));
    
            var prv_CedulaRepresentanteParameter = prv_CedulaRepresentante != null ?
                new ObjectParameter("prv_CedulaRepresentante", prv_CedulaRepresentante) :
                new ObjectParameter("prv_CedulaRepresentante", typeof(string));
    
            var prv_CedulaJuridicaParameter = prv_CedulaJuridica != null ?
                new ObjectParameter("prv_CedulaJuridica", prv_CedulaJuridica) :
                new ObjectParameter("prv_CedulaJuridica", typeof(string));
    
            var prv_TelefonoParameter = prv_Telefono != null ?
                new ObjectParameter("prv_Telefono", prv_Telefono) :
                new ObjectParameter("prv_Telefono", typeof(string));
    
            var prv_EmailParameter = prv_Email != null ?
                new ObjectParameter("prv_Email", prv_Email) :
                new ObjectParameter("prv_Email", typeof(string));
    
            var prv_TipoProveedorParameter = prv_TipoProveedor != null ?
                new ObjectParameter("prv_TipoProveedor", prv_TipoProveedor) :
                new ObjectParameter("prv_TipoProveedor", typeof(string));
    
            var v_DistritoParameter = v_Distrito.HasValue ?
                new ObjectParameter("v_Distrito", v_Distrito) :
                new ObjectParameter("v_Distrito", typeof(int));
    
            var v_CantonParameter = v_Canton.HasValue ?
                new ObjectParameter("v_Canton", v_Canton) :
                new ObjectParameter("v_Canton", typeof(int));
    
            var v_ProvinciaParameter = v_Provincia.HasValue ?
                new ObjectParameter("v_Provincia", v_Provincia) :
                new ObjectParameter("v_Provincia", typeof(int));
    
            var prv_OtrasSenasParameter = prv_OtrasSenas != null ?
                new ObjectParameter("prv_OtrasSenas", prv_OtrasSenas) :
                new ObjectParameter("prv_OtrasSenas", typeof(string));
    
            var v_ActivoParameter = v_Activo.HasValue ?
                new ObjectParameter("v_Activo", v_Activo) :
                new ObjectParameter("v_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarProveedor", prv_NombreVariableParameter, prv_NombreRepresentanteParameter, prv_PrimerApellidoParameter, prv_SegundoApellidoParameter, prv_CedulaRepresentanteParameter, prv_CedulaJuridicaParameter, prv_TelefonoParameter, prv_EmailParameter, prv_TipoProveedorParameter, v_DistritoParameter, v_CantonParameter, v_ProvinciaParameter, prv_OtrasSenasParameter, v_ActivoParameter);
        }
    
        public virtual int sp_ModificaAlquiler(Nullable<int> v_id_Propiedad, string v_UbicacionExacta, string v_TipoPropiedad, string v_Detalles, Nullable<int> v_Distrito, Nullable<int> v_Canton, Nullable<int> v_Provincia, string v_ImagenURL, Nullable<bool> v_Activo)
        {
            var v_id_PropiedadParameter = v_id_Propiedad.HasValue ?
                new ObjectParameter("v_id_Propiedad", v_id_Propiedad) :
                new ObjectParameter("v_id_Propiedad", typeof(int));
    
            var v_UbicacionExactaParameter = v_UbicacionExacta != null ?
                new ObjectParameter("v_UbicacionExacta", v_UbicacionExacta) :
                new ObjectParameter("v_UbicacionExacta", typeof(string));
    
            var v_TipoPropiedadParameter = v_TipoPropiedad != null ?
                new ObjectParameter("v_TipoPropiedad", v_TipoPropiedad) :
                new ObjectParameter("v_TipoPropiedad", typeof(string));
    
            var v_DetallesParameter = v_Detalles != null ?
                new ObjectParameter("v_Detalles", v_Detalles) :
                new ObjectParameter("v_Detalles", typeof(string));
    
            var v_DistritoParameter = v_Distrito.HasValue ?
                new ObjectParameter("v_Distrito", v_Distrito) :
                new ObjectParameter("v_Distrito", typeof(int));
    
            var v_CantonParameter = v_Canton.HasValue ?
                new ObjectParameter("v_Canton", v_Canton) :
                new ObjectParameter("v_Canton", typeof(int));
    
            var v_ProvinciaParameter = v_Provincia.HasValue ?
                new ObjectParameter("v_Provincia", v_Provincia) :
                new ObjectParameter("v_Provincia", typeof(int));
    
            var v_ImagenURLParameter = v_ImagenURL != null ?
                new ObjectParameter("v_ImagenURL", v_ImagenURL) :
                new ObjectParameter("v_ImagenURL", typeof(string));
    
            var v_ActivoParameter = v_Activo.HasValue ?
                new ObjectParameter("v_Activo", v_Activo) :
                new ObjectParameter("v_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaAlquiler", v_id_PropiedadParameter, v_UbicacionExactaParameter, v_TipoPropiedadParameter, v_DetallesParameter, v_DistritoParameter, v_CantonParameter, v_ProvinciaParameter, v_ImagenURLParameter, v_ActivoParameter);
        }
    
        public virtual int sp_ModificarAdminRental(Nullable<int> v_id_admin, string v_cedula, string v_nombre, string v_segundonombre, string v_primerapellido, string v_segundoapellido, Nullable<System.DateTime> v_fechanacimiento, string v_telefonocasa, string v_telefonocelular, string v_email)
        {
            var v_id_adminParameter = v_id_admin.HasValue ?
                new ObjectParameter("v_id_admin", v_id_admin) :
                new ObjectParameter("v_id_admin", typeof(int));
    
            var v_cedulaParameter = v_cedula != null ?
                new ObjectParameter("v_cedula", v_cedula) :
                new ObjectParameter("v_cedula", typeof(string));
    
            var v_nombreParameter = v_nombre != null ?
                new ObjectParameter("v_nombre", v_nombre) :
                new ObjectParameter("v_nombre", typeof(string));
    
            var v_segundonombreParameter = v_segundonombre != null ?
                new ObjectParameter("v_segundonombre", v_segundonombre) :
                new ObjectParameter("v_segundonombre", typeof(string));
    
            var v_primerapellidoParameter = v_primerapellido != null ?
                new ObjectParameter("v_primerapellido", v_primerapellido) :
                new ObjectParameter("v_primerapellido", typeof(string));
    
            var v_segundoapellidoParameter = v_segundoapellido != null ?
                new ObjectParameter("v_segundoapellido", v_segundoapellido) :
                new ObjectParameter("v_segundoapellido", typeof(string));
    
            var v_fechanacimientoParameter = v_fechanacimiento.HasValue ?
                new ObjectParameter("v_fechanacimiento", v_fechanacimiento) :
                new ObjectParameter("v_fechanacimiento", typeof(System.DateTime));
    
            var v_telefonocasaParameter = v_telefonocasa != null ?
                new ObjectParameter("v_telefonocasa", v_telefonocasa) :
                new ObjectParameter("v_telefonocasa", typeof(string));
    
            var v_telefonocelularParameter = v_telefonocelular != null ?
                new ObjectParameter("v_telefonocelular", v_telefonocelular) :
                new ObjectParameter("v_telefonocelular", typeof(string));
    
            var v_emailParameter = v_email != null ?
                new ObjectParameter("v_email", v_email) :
                new ObjectParameter("v_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarAdminRental", v_id_adminParameter, v_cedulaParameter, v_nombreParameter, v_segundonombreParameter, v_primerapellidoParameter, v_segundoapellidoParameter, v_fechanacimientoParameter, v_telefonocasaParameter, v_telefonocelularParameter, v_emailParameter);
        }
    
        public virtual int sp_ModificarAlquiler(Nullable<int> v_id_Propiedad, string v_UbicacionExacta, string v_TipoPropiedad, string v_Detalles, Nullable<int> v_Distrito, Nullable<int> v_Canton, Nullable<int> v_Provincia, string v_ImagenURL)
        {
            var v_id_PropiedadParameter = v_id_Propiedad.HasValue ?
                new ObjectParameter("v_id_Propiedad", v_id_Propiedad) :
                new ObjectParameter("v_id_Propiedad", typeof(int));
    
            var v_UbicacionExactaParameter = v_UbicacionExacta != null ?
                new ObjectParameter("v_UbicacionExacta", v_UbicacionExacta) :
                new ObjectParameter("v_UbicacionExacta", typeof(string));
    
            var v_TipoPropiedadParameter = v_TipoPropiedad != null ?
                new ObjectParameter("v_TipoPropiedad", v_TipoPropiedad) :
                new ObjectParameter("v_TipoPropiedad", typeof(string));
    
            var v_DetallesParameter = v_Detalles != null ?
                new ObjectParameter("v_Detalles", v_Detalles) :
                new ObjectParameter("v_Detalles", typeof(string));
    
            var v_DistritoParameter = v_Distrito.HasValue ?
                new ObjectParameter("v_Distrito", v_Distrito) :
                new ObjectParameter("v_Distrito", typeof(int));
    
            var v_CantonParameter = v_Canton.HasValue ?
                new ObjectParameter("v_Canton", v_Canton) :
                new ObjectParameter("v_Canton", typeof(int));
    
            var v_ProvinciaParameter = v_Provincia.HasValue ?
                new ObjectParameter("v_Provincia", v_Provincia) :
                new ObjectParameter("v_Provincia", typeof(int));
    
            var v_ImagenURLParameter = v_ImagenURL != null ?
                new ObjectParameter("v_ImagenURL", v_ImagenURL) :
                new ObjectParameter("v_ImagenURL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarAlquiler", v_id_PropiedadParameter, v_UbicacionExactaParameter, v_TipoPropiedadParameter, v_DetallesParameter, v_DistritoParameter, v_CantonParameter, v_ProvinciaParameter, v_ImagenURLParameter);
        }
    
        public virtual int sp_ModificarCliente(Nullable<int> id_cli_Cliente, string cli_Cedula, string cli_Nombre, string cli_SegundoNombre, string cli_PrimerApellido, string cli_SegundoApellido, Nullable<System.DateTime> cli_fechanacimiento, string cli_TelefonoCasa, string cli_TelefonoCelular, string cli_Email, Nullable<bool> v_Activo)
        {
            var id_cli_ClienteParameter = id_cli_Cliente.HasValue ?
                new ObjectParameter("id_cli_Cliente", id_cli_Cliente) :
                new ObjectParameter("id_cli_Cliente", typeof(int));
    
            var cli_CedulaParameter = cli_Cedula != null ?
                new ObjectParameter("cli_Cedula", cli_Cedula) :
                new ObjectParameter("cli_Cedula", typeof(string));
    
            var cli_NombreParameter = cli_Nombre != null ?
                new ObjectParameter("cli_Nombre", cli_Nombre) :
                new ObjectParameter("cli_Nombre", typeof(string));
    
            var cli_SegundoNombreParameter = cli_SegundoNombre != null ?
                new ObjectParameter("cli_SegundoNombre", cli_SegundoNombre) :
                new ObjectParameter("cli_SegundoNombre", typeof(string));
    
            var cli_PrimerApellidoParameter = cli_PrimerApellido != null ?
                new ObjectParameter("cli_PrimerApellido", cli_PrimerApellido) :
                new ObjectParameter("cli_PrimerApellido", typeof(string));
    
            var cli_SegundoApellidoParameter = cli_SegundoApellido != null ?
                new ObjectParameter("cli_SegundoApellido", cli_SegundoApellido) :
                new ObjectParameter("cli_SegundoApellido", typeof(string));
    
            var cli_fechanacimientoParameter = cli_fechanacimiento.HasValue ?
                new ObjectParameter("cli_fechanacimiento", cli_fechanacimiento) :
                new ObjectParameter("cli_fechanacimiento", typeof(System.DateTime));
    
            var cli_TelefonoCasaParameter = cli_TelefonoCasa != null ?
                new ObjectParameter("cli_TelefonoCasa", cli_TelefonoCasa) :
                new ObjectParameter("cli_TelefonoCasa", typeof(string));
    
            var cli_TelefonoCelularParameter = cli_TelefonoCelular != null ?
                new ObjectParameter("cli_TelefonoCelular", cli_TelefonoCelular) :
                new ObjectParameter("cli_TelefonoCelular", typeof(string));
    
            var cli_EmailParameter = cli_Email != null ?
                new ObjectParameter("cli_Email", cli_Email) :
                new ObjectParameter("cli_Email", typeof(string));
    
            var v_ActivoParameter = v_Activo.HasValue ?
                new ObjectParameter("v_Activo", v_Activo) :
                new ObjectParameter("v_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarCliente", id_cli_ClienteParameter, cli_CedulaParameter, cli_NombreParameter, cli_SegundoNombreParameter, cli_PrimerApellidoParameter, cli_SegundoApellidoParameter, cli_fechanacimientoParameter, cli_TelefonoCasaParameter, cli_TelefonoCelularParameter, cli_EmailParameter, v_ActivoParameter);
        }
    
        public virtual int sp_ModificarContrato(Nullable<int> v_id_ctr_contrato, Nullable<int> v_fk_cli_cliente, string v_ctr_numero, Nullable<System.DateTime> v_ctr_fechainicio, Nullable<System.DateTime> v_ctr_fechafinalizacion, Nullable<decimal> v_ctr_monto, Nullable<bool> v_ctr_activo, string v_ctr_file, Nullable<int> v_fk_alq_id_propiedad, Nullable<int> v_fk_adr_id_admin, Nullable<System.DateTime> v_fechaPago)
        {
            var v_id_ctr_contratoParameter = v_id_ctr_contrato.HasValue ?
                new ObjectParameter("v_id_ctr_contrato", v_id_ctr_contrato) :
                new ObjectParameter("v_id_ctr_contrato", typeof(int));
    
            var v_fk_cli_clienteParameter = v_fk_cli_cliente.HasValue ?
                new ObjectParameter("v_fk_cli_cliente", v_fk_cli_cliente) :
                new ObjectParameter("v_fk_cli_cliente", typeof(int));
    
            var v_ctr_numeroParameter = v_ctr_numero != null ?
                new ObjectParameter("v_ctr_numero", v_ctr_numero) :
                new ObjectParameter("v_ctr_numero", typeof(string));
    
            var v_ctr_fechainicioParameter = v_ctr_fechainicio.HasValue ?
                new ObjectParameter("v_ctr_fechainicio", v_ctr_fechainicio) :
                new ObjectParameter("v_ctr_fechainicio", typeof(System.DateTime));
    
            var v_ctr_fechafinalizacionParameter = v_ctr_fechafinalizacion.HasValue ?
                new ObjectParameter("v_ctr_fechafinalizacion", v_ctr_fechafinalizacion) :
                new ObjectParameter("v_ctr_fechafinalizacion", typeof(System.DateTime));
    
            var v_ctr_montoParameter = v_ctr_monto.HasValue ?
                new ObjectParameter("v_ctr_monto", v_ctr_monto) :
                new ObjectParameter("v_ctr_monto", typeof(decimal));
    
            var v_ctr_activoParameter = v_ctr_activo.HasValue ?
                new ObjectParameter("v_ctr_activo", v_ctr_activo) :
                new ObjectParameter("v_ctr_activo", typeof(bool));
    
            var v_ctr_fileParameter = v_ctr_file != null ?
                new ObjectParameter("v_ctr_file", v_ctr_file) :
                new ObjectParameter("v_ctr_file", typeof(string));
    
            var v_fk_alq_id_propiedadParameter = v_fk_alq_id_propiedad.HasValue ?
                new ObjectParameter("v_fk_alq_id_propiedad", v_fk_alq_id_propiedad) :
                new ObjectParameter("v_fk_alq_id_propiedad", typeof(int));
    
            var v_fk_adr_id_adminParameter = v_fk_adr_id_admin.HasValue ?
                new ObjectParameter("v_fk_adr_id_admin", v_fk_adr_id_admin) :
                new ObjectParameter("v_fk_adr_id_admin", typeof(int));
    
            var v_fechaPagoParameter = v_fechaPago.HasValue ?
                new ObjectParameter("v_fechaPago", v_fechaPago) :
                new ObjectParameter("v_fechaPago", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarContrato", v_id_ctr_contratoParameter, v_fk_cli_clienteParameter, v_ctr_numeroParameter, v_ctr_fechainicioParameter, v_ctr_fechafinalizacionParameter, v_ctr_montoParameter, v_ctr_activoParameter, v_ctr_fileParameter, v_fk_alq_id_propiedadParameter, v_fk_adr_id_adminParameter, v_fechaPagoParameter);
        }
    
        public virtual int sp_ModificarProveedor(Nullable<int> prv_IDProveedor, string prv_NombreVariable, string prv_NombreRepresentante, string prv_PrimerApellido, string prv_SegundoApellido, string prv_CedulaRepresentante, string prv_CedulaJuridica, string prv_Telefono, string prv_Email, string prv_TipoProveedor, Nullable<int> v_Distrito, Nullable<int> v_Canton, Nullable<int> v_Provincia, string prv_OtrasSenas, Nullable<bool> v_Activo)
        {
            var prv_IDProveedorParameter = prv_IDProveedor.HasValue ?
                new ObjectParameter("prv_IDProveedor", prv_IDProveedor) :
                new ObjectParameter("prv_IDProveedor", typeof(int));
    
            var prv_NombreVariableParameter = prv_NombreVariable != null ?
                new ObjectParameter("prv_NombreVariable", prv_NombreVariable) :
                new ObjectParameter("prv_NombreVariable", typeof(string));
    
            var prv_NombreRepresentanteParameter = prv_NombreRepresentante != null ?
                new ObjectParameter("prv_NombreRepresentante", prv_NombreRepresentante) :
                new ObjectParameter("prv_NombreRepresentante", typeof(string));
    
            var prv_PrimerApellidoParameter = prv_PrimerApellido != null ?
                new ObjectParameter("prv_PrimerApellido", prv_PrimerApellido) :
                new ObjectParameter("prv_PrimerApellido", typeof(string));
    
            var prv_SegundoApellidoParameter = prv_SegundoApellido != null ?
                new ObjectParameter("prv_SegundoApellido", prv_SegundoApellido) :
                new ObjectParameter("prv_SegundoApellido", typeof(string));
    
            var prv_CedulaRepresentanteParameter = prv_CedulaRepresentante != null ?
                new ObjectParameter("prv_CedulaRepresentante", prv_CedulaRepresentante) :
                new ObjectParameter("prv_CedulaRepresentante", typeof(string));
    
            var prv_CedulaJuridicaParameter = prv_CedulaJuridica != null ?
                new ObjectParameter("prv_CedulaJuridica", prv_CedulaJuridica) :
                new ObjectParameter("prv_CedulaJuridica", typeof(string));
    
            var prv_TelefonoParameter = prv_Telefono != null ?
                new ObjectParameter("prv_Telefono", prv_Telefono) :
                new ObjectParameter("prv_Telefono", typeof(string));
    
            var prv_EmailParameter = prv_Email != null ?
                new ObjectParameter("prv_Email", prv_Email) :
                new ObjectParameter("prv_Email", typeof(string));
    
            var prv_TipoProveedorParameter = prv_TipoProveedor != null ?
                new ObjectParameter("prv_TipoProveedor", prv_TipoProveedor) :
                new ObjectParameter("prv_TipoProveedor", typeof(string));
    
            var v_DistritoParameter = v_Distrito.HasValue ?
                new ObjectParameter("v_Distrito", v_Distrito) :
                new ObjectParameter("v_Distrito", typeof(int));
    
            var v_CantonParameter = v_Canton.HasValue ?
                new ObjectParameter("v_Canton", v_Canton) :
                new ObjectParameter("v_Canton", typeof(int));
    
            var v_ProvinciaParameter = v_Provincia.HasValue ?
                new ObjectParameter("v_Provincia", v_Provincia) :
                new ObjectParameter("v_Provincia", typeof(int));
    
            var prv_OtrasSenasParameter = prv_OtrasSenas != null ?
                new ObjectParameter("prv_OtrasSenas", prv_OtrasSenas) :
                new ObjectParameter("prv_OtrasSenas", typeof(string));
    
            var v_ActivoParameter = v_Activo.HasValue ?
                new ObjectParameter("v_Activo", v_Activo) :
                new ObjectParameter("v_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarProveedor", prv_IDProveedorParameter, prv_NombreVariableParameter, prv_NombreRepresentanteParameter, prv_PrimerApellidoParameter, prv_SegundoApellidoParameter, prv_CedulaRepresentanteParameter, prv_CedulaJuridicaParameter, prv_TelefonoParameter, prv_EmailParameter, prv_TipoProveedorParameter, v_DistritoParameter, v_CantonParameter, v_ProvinciaParameter, prv_OtrasSenasParameter, v_ActivoParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_RetornaAdminRental_Result> sp_RetornaAdminRental(string v_cedula, string v_nombre, string v_segundonombre, string v_apellido, string v_segundoapellido, string v_email)
        {
            var v_cedulaParameter = v_cedula != null ?
                new ObjectParameter("v_cedula", v_cedula) :
                new ObjectParameter("v_cedula", typeof(string));
    
            var v_nombreParameter = v_nombre != null ?
                new ObjectParameter("v_nombre", v_nombre) :
                new ObjectParameter("v_nombre", typeof(string));
    
            var v_segundonombreParameter = v_segundonombre != null ?
                new ObjectParameter("v_segundonombre", v_segundonombre) :
                new ObjectParameter("v_segundonombre", typeof(string));
    
            var v_apellidoParameter = v_apellido != null ?
                new ObjectParameter("v_apellido", v_apellido) :
                new ObjectParameter("v_apellido", typeof(string));
    
            var v_segundoapellidoParameter = v_segundoapellido != null ?
                new ObjectParameter("v_segundoapellido", v_segundoapellido) :
                new ObjectParameter("v_segundoapellido", typeof(string));
    
            var v_emailParameter = v_email != null ?
                new ObjectParameter("v_email", v_email) :
                new ObjectParameter("v_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaAdminRental_Result>("sp_RetornaAdminRental", v_cedulaParameter, v_nombreParameter, v_segundonombreParameter, v_apellidoParameter, v_segundoapellidoParameter, v_emailParameter);
        }
    
        public virtual ObjectResult<sp_RetornaAdminRentalID_Result> sp_RetornaAdminRentalID(Nullable<int> id_admin)
        {
            var id_adminParameter = id_admin.HasValue ?
                new ObjectParameter("id_admin", id_admin) :
                new ObjectParameter("id_admin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaAdminRentalID_Result>("sp_RetornaAdminRentalID", id_adminParameter);
        }
    
        public virtual ObjectResult<sp_RetornaAlquiler_Result> sp_RetornaAlquiler(Nullable<int> v_alq_id_Propiedad, string v_alq_tipo_Propiedad, Nullable<int> v_Provincia, Nullable<bool> v_Activo)
        {
            var v_alq_id_PropiedadParameter = v_alq_id_Propiedad.HasValue ?
                new ObjectParameter("v_alq_id_Propiedad", v_alq_id_Propiedad) :
                new ObjectParameter("v_alq_id_Propiedad", typeof(int));
    
            var v_alq_tipo_PropiedadParameter = v_alq_tipo_Propiedad != null ?
                new ObjectParameter("v_alq_tipo_Propiedad", v_alq_tipo_Propiedad) :
                new ObjectParameter("v_alq_tipo_Propiedad", typeof(string));
    
            var v_ProvinciaParameter = v_Provincia.HasValue ?
                new ObjectParameter("v_Provincia", v_Provincia) :
                new ObjectParameter("v_Provincia", typeof(int));
    
            var v_ActivoParameter = v_Activo.HasValue ?
                new ObjectParameter("v_Activo", v_Activo) :
                new ObjectParameter("v_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaAlquiler_Result>("sp_RetornaAlquiler", v_alq_id_PropiedadParameter, v_alq_tipo_PropiedadParameter, v_ProvinciaParameter, v_ActivoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaAlquilerDataGrid_Result> sp_RetornaAlquilerDataGrid(Nullable<bool> v_alq_activo)
        {
            var v_alq_activoParameter = v_alq_activo.HasValue ?
                new ObjectParameter("v_alq_activo", v_alq_activo) :
                new ObjectParameter("v_alq_activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaAlquilerDataGrid_Result>("sp_RetornaAlquilerDataGrid", v_alq_activoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaAlquilerID_Result> sp_RetornaAlquilerID(Nullable<int> id_Propiedad)
        {
            var id_PropiedadParameter = id_Propiedad.HasValue ?
                new ObjectParameter("id_Propiedad", id_Propiedad) :
                new ObjectParameter("id_Propiedad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaAlquilerID_Result>("sp_RetornaAlquilerID", id_PropiedadParameter);
        }
    
        public virtual ObjectResult<sp_RetornaCliente_Result> sp_RetornaCliente(string cli_Cedula, string cli_Nombre, string cli_SegundoNombre, string cli_PrimerApellido, string cli_SegundoApellido, string cli_TelefonoCasa, string cli_TelefonoCelular, string cli_Email, Nullable<bool> v_Activo)
        {
            var cli_CedulaParameter = cli_Cedula != null ?
                new ObjectParameter("cli_Cedula", cli_Cedula) :
                new ObjectParameter("cli_Cedula", typeof(string));
    
            var cli_NombreParameter = cli_Nombre != null ?
                new ObjectParameter("cli_Nombre", cli_Nombre) :
                new ObjectParameter("cli_Nombre", typeof(string));
    
            var cli_SegundoNombreParameter = cli_SegundoNombre != null ?
                new ObjectParameter("cli_SegundoNombre", cli_SegundoNombre) :
                new ObjectParameter("cli_SegundoNombre", typeof(string));
    
            var cli_PrimerApellidoParameter = cli_PrimerApellido != null ?
                new ObjectParameter("cli_PrimerApellido", cli_PrimerApellido) :
                new ObjectParameter("cli_PrimerApellido", typeof(string));
    
            var cli_SegundoApellidoParameter = cli_SegundoApellido != null ?
                new ObjectParameter("cli_SegundoApellido", cli_SegundoApellido) :
                new ObjectParameter("cli_SegundoApellido", typeof(string));
    
            var cli_TelefonoCasaParameter = cli_TelefonoCasa != null ?
                new ObjectParameter("cli_TelefonoCasa", cli_TelefonoCasa) :
                new ObjectParameter("cli_TelefonoCasa", typeof(string));
    
            var cli_TelefonoCelularParameter = cli_TelefonoCelular != null ?
                new ObjectParameter("cli_TelefonoCelular", cli_TelefonoCelular) :
                new ObjectParameter("cli_TelefonoCelular", typeof(string));
    
            var cli_EmailParameter = cli_Email != null ?
                new ObjectParameter("cli_Email", cli_Email) :
                new ObjectParameter("cli_Email", typeof(string));
    
            var v_ActivoParameter = v_Activo.HasValue ?
                new ObjectParameter("v_Activo", v_Activo) :
                new ObjectParameter("v_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCliente_Result>("sp_RetornaCliente", cli_CedulaParameter, cli_NombreParameter, cli_SegundoNombreParameter, cli_PrimerApellidoParameter, cli_SegundoApellidoParameter, cli_TelefonoCasaParameter, cli_TelefonoCelularParameter, cli_EmailParameter, v_ActivoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaClienteID_Result> sp_RetornaClienteID(Nullable<int> id_IDCliente)
        {
            var id_IDClienteParameter = id_IDCliente.HasValue ?
                new ObjectParameter("id_IDCliente", id_IDCliente) :
                new ObjectParameter("id_IDCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaClienteID_Result>("sp_RetornaClienteID", id_IDClienteParameter);
        }
    
        public virtual ObjectResult<sp_RetornaContrato_Result> sp_RetornaContrato(Nullable<int> v_id_ctr_contrato, Nullable<int> v_fk_cli_cliente, string v_ctr_numero, Nullable<bool> v_ctr_activo, Nullable<int> v_fk_adr_id_admin)
        {
            var v_id_ctr_contratoParameter = v_id_ctr_contrato.HasValue ?
                new ObjectParameter("v_id_ctr_contrato", v_id_ctr_contrato) :
                new ObjectParameter("v_id_ctr_contrato", typeof(int));
    
            var v_fk_cli_clienteParameter = v_fk_cli_cliente.HasValue ?
                new ObjectParameter("v_fk_cli_cliente", v_fk_cli_cliente) :
                new ObjectParameter("v_fk_cli_cliente", typeof(int));
    
            var v_ctr_numeroParameter = v_ctr_numero != null ?
                new ObjectParameter("v_ctr_numero", v_ctr_numero) :
                new ObjectParameter("v_ctr_numero", typeof(string));
    
            var v_ctr_activoParameter = v_ctr_activo.HasValue ?
                new ObjectParameter("v_ctr_activo", v_ctr_activo) :
                new ObjectParameter("v_ctr_activo", typeof(bool));
    
            var v_fk_adr_id_adminParameter = v_fk_adr_id_admin.HasValue ?
                new ObjectParameter("v_fk_adr_id_admin", v_fk_adr_id_admin) :
                new ObjectParameter("v_fk_adr_id_admin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaContrato_Result>("sp_RetornaContrato", v_id_ctr_contratoParameter, v_fk_cli_clienteParameter, v_ctr_numeroParameter, v_ctr_activoParameter, v_fk_adr_id_adminParameter);
        }
    
        public virtual ObjectResult<sp_RetornaContratoDataGrid_Result> sp_RetornaContratoDataGrid(Nullable<bool> v_ctr_activo, Nullable<int> v_fk_adr_id_admin)
        {
            var v_ctr_activoParameter = v_ctr_activo.HasValue ?
                new ObjectParameter("v_ctr_activo", v_ctr_activo) :
                new ObjectParameter("v_ctr_activo", typeof(bool));
    
            var v_fk_adr_id_adminParameter = v_fk_adr_id_admin.HasValue ?
                new ObjectParameter("v_fk_adr_id_admin", v_fk_adr_id_admin) :
                new ObjectParameter("v_fk_adr_id_admin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaContratoDataGrid_Result>("sp_RetornaContratoDataGrid", v_ctr_activoParameter, v_fk_adr_id_adminParameter);
        }
    
        public virtual ObjectResult<sp_RetornaContratoID_Result> sp_RetornaContratoID(Nullable<int> v_id_contrato)
        {
            var v_id_contratoParameter = v_id_contrato.HasValue ?
                new ObjectParameter("v_id_contrato", v_id_contrato) :
                new ObjectParameter("v_id_contrato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaContratoID_Result>("sp_RetornaContratoID", v_id_contratoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaProveedorID_Result> sp_RetornaProveedorID(Nullable<int> prv_IDProveedor)
        {
            var prv_IDProveedorParameter = prv_IDProveedor.HasValue ?
                new ObjectParameter("prv_IDProveedor", prv_IDProveedor) :
                new ObjectParameter("prv_IDProveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaProveedorID_Result>("sp_RetornaProveedorID", prv_IDProveedorParameter);
        }
    
        public virtual ObjectResult<sp_RetornarProveedor_Result> sp_RetornarProveedor(string prv_NombreRepresentante, string prv_CedulaRepresentante, string prv_CedulaJuridica, string prv_Email, Nullable<bool> v_Activo)
        {
            var prv_NombreRepresentanteParameter = prv_NombreRepresentante != null ?
                new ObjectParameter("prv_NombreRepresentante", prv_NombreRepresentante) :
                new ObjectParameter("prv_NombreRepresentante", typeof(string));
    
            var prv_CedulaRepresentanteParameter = prv_CedulaRepresentante != null ?
                new ObjectParameter("prv_CedulaRepresentante", prv_CedulaRepresentante) :
                new ObjectParameter("prv_CedulaRepresentante", typeof(string));
    
            var prv_CedulaJuridicaParameter = prv_CedulaJuridica != null ?
                new ObjectParameter("prv_CedulaJuridica", prv_CedulaJuridica) :
                new ObjectParameter("prv_CedulaJuridica", typeof(string));
    
            var prv_EmailParameter = prv_Email != null ?
                new ObjectParameter("prv_Email", prv_Email) :
                new ObjectParameter("prv_Email", typeof(string));
    
            var v_ActivoParameter = v_Activo.HasValue ?
                new ObjectParameter("v_Activo", v_Activo) :
                new ObjectParameter("v_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornarProveedor_Result>("sp_RetornarProveedor", prv_NombreRepresentanteParameter, prv_CedulaRepresentanteParameter, prv_CedulaJuridicaParameter, prv_EmailParameter, v_ActivoParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<sp_BuscaContratoDataGrid_Result> sp_BuscaContratoDataGrid(string v_ctr_numeroContrato)
        {
            var v_ctr_numeroContratoParameter = v_ctr_numeroContrato != null ?
                new ObjectParameter("v_ctr_numeroContrato", v_ctr_numeroContrato) :
                new ObjectParameter("v_ctr_numeroContrato", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscaContratoDataGrid_Result>("sp_BuscaContratoDataGrid", v_ctr_numeroContratoParameter);
        }
    
        public virtual int sp_InsertarTiquete(Nullable<int> v_fk_ctr_contrato, string v_tqt_tipo_problema, Nullable<bool> v_tqt_activo, string v_tqt_descripcion, string v_tqt_nota_reparacion, Nullable<System.DateTime> v_tqt_fecha_inicio, Nullable<System.DateTime> v_tqt_fecha_finalizacion, Nullable<int> v_fk_prv_idproveedor, string v_tqt_titulo, Nullable<decimal> v_tqt_precio_preparacion, string v_tqt_estado)
        {
            var v_fk_ctr_contratoParameter = v_fk_ctr_contrato.HasValue ?
                new ObjectParameter("v_fk_ctr_contrato", v_fk_ctr_contrato) :
                new ObjectParameter("v_fk_ctr_contrato", typeof(int));
    
            var v_tqt_tipo_problemaParameter = v_tqt_tipo_problema != null ?
                new ObjectParameter("v_tqt_tipo_problema", v_tqt_tipo_problema) :
                new ObjectParameter("v_tqt_tipo_problema", typeof(string));
    
            var v_tqt_activoParameter = v_tqt_activo.HasValue ?
                new ObjectParameter("v_tqt_activo", v_tqt_activo) :
                new ObjectParameter("v_tqt_activo", typeof(bool));
    
            var v_tqt_descripcionParameter = v_tqt_descripcion != null ?
                new ObjectParameter("v_tqt_descripcion", v_tqt_descripcion) :
                new ObjectParameter("v_tqt_descripcion", typeof(string));
    
            var v_tqt_nota_reparacionParameter = v_tqt_nota_reparacion != null ?
                new ObjectParameter("v_tqt_nota_reparacion", v_tqt_nota_reparacion) :
                new ObjectParameter("v_tqt_nota_reparacion", typeof(string));
    
            var v_tqt_fecha_inicioParameter = v_tqt_fecha_inicio.HasValue ?
                new ObjectParameter("v_tqt_fecha_inicio", v_tqt_fecha_inicio) :
                new ObjectParameter("v_tqt_fecha_inicio", typeof(System.DateTime));
    
            var v_tqt_fecha_finalizacionParameter = v_tqt_fecha_finalizacion.HasValue ?
                new ObjectParameter("v_tqt_fecha_finalizacion", v_tqt_fecha_finalizacion) :
                new ObjectParameter("v_tqt_fecha_finalizacion", typeof(System.DateTime));
    
            var v_fk_prv_idproveedorParameter = v_fk_prv_idproveedor.HasValue ?
                new ObjectParameter("v_fk_prv_idproveedor", v_fk_prv_idproveedor) :
                new ObjectParameter("v_fk_prv_idproveedor", typeof(int));
    
            var v_tqt_tituloParameter = v_tqt_titulo != null ?
                new ObjectParameter("v_tqt_titulo", v_tqt_titulo) :
                new ObjectParameter("v_tqt_titulo", typeof(string));
    
            var v_tqt_precio_preparacionParameter = v_tqt_precio_preparacion.HasValue ?
                new ObjectParameter("v_tqt_precio_preparacion", v_tqt_precio_preparacion) :
                new ObjectParameter("v_tqt_precio_preparacion", typeof(decimal));
    
            var v_tqt_estadoParameter = v_tqt_estado != null ?
                new ObjectParameter("v_tqt_estado", v_tqt_estado) :
                new ObjectParameter("v_tqt_estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarTiquete", v_fk_ctr_contratoParameter, v_tqt_tipo_problemaParameter, v_tqt_activoParameter, v_tqt_descripcionParameter, v_tqt_nota_reparacionParameter, v_tqt_fecha_inicioParameter, v_tqt_fecha_finalizacionParameter, v_fk_prv_idproveedorParameter, v_tqt_tituloParameter, v_tqt_precio_preparacionParameter, v_tqt_estadoParameter);
        }
    
        public virtual int sp_ModificarTiquete(Nullable<int> v_tqt_id, Nullable<int> v_id_ctr_contrato, string v_tqt_tipo_problema, Nullable<bool> v_tqt_activo, string v_tqt_descripcion, string v_tqt_nota_reparacion, Nullable<System.DateTime> v_tqt_fechainicio, Nullable<System.DateTime> v_tqt_fechafinalizacion, Nullable<int> v_fk_prv_idProveedor, string v_tqt_titulo, Nullable<decimal> v_tqt_monto, string v_tqt_estado)
        {
            var v_tqt_idParameter = v_tqt_id.HasValue ?
                new ObjectParameter("v_tqt_id", v_tqt_id) :
                new ObjectParameter("v_tqt_id", typeof(int));
    
            var v_id_ctr_contratoParameter = v_id_ctr_contrato.HasValue ?
                new ObjectParameter("v_id_ctr_contrato", v_id_ctr_contrato) :
                new ObjectParameter("v_id_ctr_contrato", typeof(int));
    
            var v_tqt_tipo_problemaParameter = v_tqt_tipo_problema != null ?
                new ObjectParameter("v_tqt_tipo_problema", v_tqt_tipo_problema) :
                new ObjectParameter("v_tqt_tipo_problema", typeof(string));
    
            var v_tqt_activoParameter = v_tqt_activo.HasValue ?
                new ObjectParameter("v_tqt_activo", v_tqt_activo) :
                new ObjectParameter("v_tqt_activo", typeof(bool));
    
            var v_tqt_descripcionParameter = v_tqt_descripcion != null ?
                new ObjectParameter("v_tqt_descripcion", v_tqt_descripcion) :
                new ObjectParameter("v_tqt_descripcion", typeof(string));
    
            var v_tqt_nota_reparacionParameter = v_tqt_nota_reparacion != null ?
                new ObjectParameter("v_tqt_nota_reparacion", v_tqt_nota_reparacion) :
                new ObjectParameter("v_tqt_nota_reparacion", typeof(string));
    
            var v_tqt_fechainicioParameter = v_tqt_fechainicio.HasValue ?
                new ObjectParameter("v_tqt_fechainicio", v_tqt_fechainicio) :
                new ObjectParameter("v_tqt_fechainicio", typeof(System.DateTime));
    
            var v_tqt_fechafinalizacionParameter = v_tqt_fechafinalizacion.HasValue ?
                new ObjectParameter("v_tqt_fechafinalizacion", v_tqt_fechafinalizacion) :
                new ObjectParameter("v_tqt_fechafinalizacion", typeof(System.DateTime));
    
            var v_fk_prv_idProveedorParameter = v_fk_prv_idProveedor.HasValue ?
                new ObjectParameter("v_fk_prv_idProveedor", v_fk_prv_idProveedor) :
                new ObjectParameter("v_fk_prv_idProveedor", typeof(int));
    
            var v_tqt_tituloParameter = v_tqt_titulo != null ?
                new ObjectParameter("v_tqt_titulo", v_tqt_titulo) :
                new ObjectParameter("v_tqt_titulo", typeof(string));
    
            var v_tqt_montoParameter = v_tqt_monto.HasValue ?
                new ObjectParameter("v_tqt_monto", v_tqt_monto) :
                new ObjectParameter("v_tqt_monto", typeof(decimal));
    
            var v_tqt_estadoParameter = v_tqt_estado != null ?
                new ObjectParameter("v_tqt_estado", v_tqt_estado) :
                new ObjectParameter("v_tqt_estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarTiquete", v_tqt_idParameter, v_id_ctr_contratoParameter, v_tqt_tipo_problemaParameter, v_tqt_activoParameter, v_tqt_descripcionParameter, v_tqt_nota_reparacionParameter, v_tqt_fechainicioParameter, v_tqt_fechafinalizacionParameter, v_fk_prv_idProveedorParameter, v_tqt_tituloParameter, v_tqt_montoParameter, v_tqt_estadoParameter);
        }
    
        public virtual int sp_ModificarTiquetexProveedor(Nullable<int> v_tqt_id, string v_tqt_nota_reparacion, Nullable<System.DateTime> v_tqt_fechafinalizacion, Nullable<decimal> v_tqt_monto, string v_tqt_estado)
        {
            var v_tqt_idParameter = v_tqt_id.HasValue ?
                new ObjectParameter("v_tqt_id", v_tqt_id) :
                new ObjectParameter("v_tqt_id", typeof(int));
    
            var v_tqt_nota_reparacionParameter = v_tqt_nota_reparacion != null ?
                new ObjectParameter("v_tqt_nota_reparacion", v_tqt_nota_reparacion) :
                new ObjectParameter("v_tqt_nota_reparacion", typeof(string));
    
            var v_tqt_fechafinalizacionParameter = v_tqt_fechafinalizacion.HasValue ?
                new ObjectParameter("v_tqt_fechafinalizacion", v_tqt_fechafinalizacion) :
                new ObjectParameter("v_tqt_fechafinalizacion", typeof(System.DateTime));
    
            var v_tqt_montoParameter = v_tqt_monto.HasValue ?
                new ObjectParameter("v_tqt_monto", v_tqt_monto) :
                new ObjectParameter("v_tqt_monto", typeof(decimal));
    
            var v_tqt_estadoParameter = v_tqt_estado != null ?
                new ObjectParameter("v_tqt_estado", v_tqt_estado) :
                new ObjectParameter("v_tqt_estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarTiquetexProveedor", v_tqt_idParameter, v_tqt_nota_reparacionParameter, v_tqt_fechafinalizacionParameter, v_tqt_montoParameter, v_tqt_estadoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_RetornaCantidadContratos(Nullable<bool> ctr_activo, Nullable<int> ctr_cliente)
        {
            var ctr_activoParameter = ctr_activo.HasValue ?
                new ObjectParameter("ctr_activo", ctr_activo) :
                new ObjectParameter("ctr_activo", typeof(bool));
    
            var ctr_clienteParameter = ctr_cliente.HasValue ?
                new ObjectParameter("ctr_cliente", ctr_cliente) :
                new ObjectParameter("ctr_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_RetornaCantidadContratos", ctr_activoParameter, ctr_clienteParameter);
        }
    
        public virtual ObjectResult<sp_RetornaProveedorDataGrid_Result> sp_RetornaProveedorDataGrid(Nullable<bool> v_alq_activo)
        {
            var v_alq_activoParameter = v_alq_activo.HasValue ?
                new ObjectParameter("v_alq_activo", v_alq_activo) :
                new ObjectParameter("v_alq_activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaProveedorDataGrid_Result>("sp_RetornaProveedorDataGrid", v_alq_activoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaTiqueteID_Result> sp_RetornaTiqueteID(Nullable<int> v_tqt_id)
        {
            var v_tqt_idParameter = v_tqt_id.HasValue ?
                new ObjectParameter("v_tqt_id", v_tqt_id) :
                new ObjectParameter("v_tqt_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaTiqueteID_Result>("sp_RetornaTiqueteID", v_tqt_idParameter);
        }
    
        public virtual ObjectResult<sp_RetornaTiquetesDataGrid_Result> sp_RetornaTiquetesDataGrid(Nullable<bool> v_tqr_activo, Nullable<int> v_fk_adr_id_admin, Nullable<int> v_fk_cli_client, Nullable<int> v_fk_prv_proveedor, string v_tqt_estado)
        {
            var v_tqr_activoParameter = v_tqr_activo.HasValue ?
                new ObjectParameter("v_tqr_activo", v_tqr_activo) :
                new ObjectParameter("v_tqr_activo", typeof(bool));
    
            var v_fk_adr_id_adminParameter = v_fk_adr_id_admin.HasValue ?
                new ObjectParameter("v_fk_adr_id_admin", v_fk_adr_id_admin) :
                new ObjectParameter("v_fk_adr_id_admin", typeof(int));
    
            var v_fk_cli_clientParameter = v_fk_cli_client.HasValue ?
                new ObjectParameter("v_fk_cli_client", v_fk_cli_client) :
                new ObjectParameter("v_fk_cli_client", typeof(int));
    
            var v_fk_prv_proveedorParameter = v_fk_prv_proveedor.HasValue ?
                new ObjectParameter("v_fk_prv_proveedor", v_fk_prv_proveedor) :
                new ObjectParameter("v_fk_prv_proveedor", typeof(int));
    
            var v_tqt_estadoParameter = v_tqt_estado != null ?
                new ObjectParameter("v_tqt_estado", v_tqt_estado) :
                new ObjectParameter("v_tqt_estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaTiquetesDataGrid_Result>("sp_RetornaTiquetesDataGrid", v_tqr_activoParameter, v_fk_adr_id_adminParameter, v_fk_cli_clientParameter, v_fk_prv_proveedorParameter, v_tqt_estadoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaUsuarioUserID_Result> sp_RetornaUsuarioUserID(string v_usuario)
        {
            var v_usuarioParameter = v_usuario != null ?
                new ObjectParameter("v_usuario", v_usuario) :
                new ObjectParameter("v_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaUsuarioUserID_Result>("sp_RetornaUsuarioUserID", v_usuarioParameter);
        }
    
        public virtual ObjectResult<sp_RetornaContratoDataGridMod_Result> sp_RetornaContratoDataGridMod(Nullable<bool> v_ctr_activo)
        {
            var v_ctr_activoParameter = v_ctr_activo.HasValue ?
                new ObjectParameter("v_ctr_activo", v_ctr_activo) :
                new ObjectParameter("v_ctr_activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaContratoDataGridMod_Result>("sp_RetornaContratoDataGridMod", v_ctr_activoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaGastosCalend_Result> sp_RetornaGastosCalend(Nullable<System.DateTime> v_inicio, Nullable<System.DateTime> v_final)
        {
            var v_inicioParameter = v_inicio.HasValue ?
                new ObjectParameter("v_inicio", v_inicio) :
                new ObjectParameter("v_inicio", typeof(System.DateTime));
    
            var v_finalParameter = v_final.HasValue ?
                new ObjectParameter("v_final", v_final) :
                new ObjectParameter("v_final", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaGastosCalend_Result>("sp_RetornaGastosCalend", v_inicioParameter, v_finalParameter);
        }
    
        public virtual ObjectResult<sp_RetornaGastosCat_Result> sp_RetornaGastosCat(string v_cat)
        {
            var v_catParameter = v_cat != null ?
                new ObjectParameter("v_cat", v_cat) :
                new ObjectParameter("v_cat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaGastosCat_Result>("sp_RetornaGastosCat", v_catParameter);
        }
    
        public virtual int sp_ModificarProveedor_Elimina(Nullable<int> prv_IDProveedor, string prv_NombreVariable, string prv_NombreRepresentante, string prv_PrimerApellido, string prv_SegundoApellido, string prv_CedulaRepresentante, string prv_CedulaJuridica, string prv_Telefono, string prv_Email, string prv_TipoProveedor, Nullable<int> v_Provincia, string prv_OtrasSenas, Nullable<bool> v_Activo)
        {
            var prv_IDProveedorParameter = prv_IDProveedor.HasValue ?
                new ObjectParameter("prv_IDProveedor", prv_IDProveedor) :
                new ObjectParameter("prv_IDProveedor", typeof(int));
    
            var prv_NombreVariableParameter = prv_NombreVariable != null ?
                new ObjectParameter("prv_NombreVariable", prv_NombreVariable) :
                new ObjectParameter("prv_NombreVariable", typeof(string));
    
            var prv_NombreRepresentanteParameter = prv_NombreRepresentante != null ?
                new ObjectParameter("prv_NombreRepresentante", prv_NombreRepresentante) :
                new ObjectParameter("prv_NombreRepresentante", typeof(string));
    
            var prv_PrimerApellidoParameter = prv_PrimerApellido != null ?
                new ObjectParameter("prv_PrimerApellido", prv_PrimerApellido) :
                new ObjectParameter("prv_PrimerApellido", typeof(string));
    
            var prv_SegundoApellidoParameter = prv_SegundoApellido != null ?
                new ObjectParameter("prv_SegundoApellido", prv_SegundoApellido) :
                new ObjectParameter("prv_SegundoApellido", typeof(string));
    
            var prv_CedulaRepresentanteParameter = prv_CedulaRepresentante != null ?
                new ObjectParameter("prv_CedulaRepresentante", prv_CedulaRepresentante) :
                new ObjectParameter("prv_CedulaRepresentante", typeof(string));
    
            var prv_CedulaJuridicaParameter = prv_CedulaJuridica != null ?
                new ObjectParameter("prv_CedulaJuridica", prv_CedulaJuridica) :
                new ObjectParameter("prv_CedulaJuridica", typeof(string));
    
            var prv_TelefonoParameter = prv_Telefono != null ?
                new ObjectParameter("prv_Telefono", prv_Telefono) :
                new ObjectParameter("prv_Telefono", typeof(string));
    
            var prv_EmailParameter = prv_Email != null ?
                new ObjectParameter("prv_Email", prv_Email) :
                new ObjectParameter("prv_Email", typeof(string));
    
            var prv_TipoProveedorParameter = prv_TipoProveedor != null ?
                new ObjectParameter("prv_TipoProveedor", prv_TipoProveedor) :
                new ObjectParameter("prv_TipoProveedor", typeof(string));
    
            var v_ProvinciaParameter = v_Provincia.HasValue ?
                new ObjectParameter("v_Provincia", v_Provincia) :
                new ObjectParameter("v_Provincia", typeof(int));
    
            var prv_OtrasSenasParameter = prv_OtrasSenas != null ?
                new ObjectParameter("prv_OtrasSenas", prv_OtrasSenas) :
                new ObjectParameter("prv_OtrasSenas", typeof(string));
    
            var v_ActivoParameter = v_Activo.HasValue ?
                new ObjectParameter("v_Activo", v_Activo) :
                new ObjectParameter("v_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarProveedor_Elimina", prv_IDProveedorParameter, prv_NombreVariableParameter, prv_NombreRepresentanteParameter, prv_PrimerApellidoParameter, prv_SegundoApellidoParameter, prv_CedulaRepresentanteParameter, prv_CedulaJuridicaParameter, prv_TelefonoParameter, prv_EmailParameter, prv_TipoProveedorParameter, v_ProvinciaParameter, prv_OtrasSenasParameter, v_ActivoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaClienteDataGrid_Result> sp_RetornaClienteDataGrid(Nullable<bool> v_alq_activo)
        {
            var v_alq_activoParameter = v_alq_activo.HasValue ?
                new ObjectParameter("v_alq_activo", v_alq_activo) :
                new ObjectParameter("v_alq_activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaClienteDataGrid_Result>("sp_RetornaClienteDataGrid", v_alq_activoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaReporteAdmin_Result> sp_RetornaReporteAdmin(Nullable<int> v_fk_adr_id_admin, Nullable<int> v_fk_ctr_cliente, Nullable<int> v_fk_prv_proveedor, string v_estado, Nullable<System.DateTime> v_fecha_inicio1, Nullable<System.DateTime> v_fecha_inicio2, Nullable<System.DateTime> v_fecha_finalizacion1, Nullable<System.DateTime> v_fecha_finalizacion2, Nullable<int> v_ctr_contrato)
        {
            var v_fk_adr_id_adminParameter = v_fk_adr_id_admin.HasValue ?
                new ObjectParameter("v_fk_adr_id_admin", v_fk_adr_id_admin) :
                new ObjectParameter("v_fk_adr_id_admin", typeof(int));
    
            var v_fk_ctr_clienteParameter = v_fk_ctr_cliente.HasValue ?
                new ObjectParameter("v_fk_ctr_cliente", v_fk_ctr_cliente) :
                new ObjectParameter("v_fk_ctr_cliente", typeof(int));
    
            var v_fk_prv_proveedorParameter = v_fk_prv_proveedor.HasValue ?
                new ObjectParameter("v_fk_prv_proveedor", v_fk_prv_proveedor) :
                new ObjectParameter("v_fk_prv_proveedor", typeof(int));
    
            var v_estadoParameter = v_estado != null ?
                new ObjectParameter("v_estado", v_estado) :
                new ObjectParameter("v_estado", typeof(string));
    
            var v_fecha_inicio1Parameter = v_fecha_inicio1.HasValue ?
                new ObjectParameter("v_fecha_inicio1", v_fecha_inicio1) :
                new ObjectParameter("v_fecha_inicio1", typeof(System.DateTime));
    
            var v_fecha_inicio2Parameter = v_fecha_inicio2.HasValue ?
                new ObjectParameter("v_fecha_inicio2", v_fecha_inicio2) :
                new ObjectParameter("v_fecha_inicio2", typeof(System.DateTime));
    
            var v_fecha_finalizacion1Parameter = v_fecha_finalizacion1.HasValue ?
                new ObjectParameter("v_fecha_finalizacion1", v_fecha_finalizacion1) :
                new ObjectParameter("v_fecha_finalizacion1", typeof(System.DateTime));
    
            var v_fecha_finalizacion2Parameter = v_fecha_finalizacion2.HasValue ?
                new ObjectParameter("v_fecha_finalizacion2", v_fecha_finalizacion2) :
                new ObjectParameter("v_fecha_finalizacion2", typeof(System.DateTime));
    
            var v_ctr_contratoParameter = v_ctr_contrato.HasValue ?
                new ObjectParameter("v_ctr_contrato", v_ctr_contrato) :
                new ObjectParameter("v_ctr_contrato", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaReporteAdmin_Result>("sp_RetornaReporteAdmin", v_fk_adr_id_adminParameter, v_fk_ctr_clienteParameter, v_fk_prv_proveedorParameter, v_estadoParameter, v_fecha_inicio1Parameter, v_fecha_inicio2Parameter, v_fecha_finalizacion1Parameter, v_fecha_finalizacion2Parameter, v_ctr_contratoParameter);
        }
    }
}
